# -*- coding: utf-8 -*-
"""AERPythonBatteryAnalysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QGmRpfnGQDFsec2bgcAzK1GYxFRVzUgI
"""

import pandas as pd
import matplotlib.pyplot as plt

# Read the CSV data and process it
current_voltage_readings = pd.read_csv('Charlie-DataLog-9-24.csv', skiprows=13, usecols=['Time', 'D1 DC Bus Voltage', 'D4 DC Bus Current'])
current_voltage_readings = current_voltage_readings.drop(0)

for col in current_voltage_readings.columns:
    current_voltage_readings[col] = current_voltage_readings[col].astype(float)

current_voltage_readings['Wattage'] = current_voltage_readings['D1 DC Bus Voltage'] * current_voltage_readings['D4 DC Bus Current']

current_voltage_readings = current_voltage_readings[current_voltage_readings['D4 DC Bus Current'] > 1]

# Plot the data as dots (scatter plot)
plt.plot(current_voltage_readings["Time"], current_voltage_readings["Wattage"])
plt.show()

# Calculate the mean of the 'Wattage' column
mean_wattage = current_voltage_readings['Wattage'].mean()

# Print the mean value
print("Mean Wattage:", mean_wattage)

# Print the entire dataframe if needed
# print(current_voltage_readings)